---
title: "demo_web"
format: 
  html
---

```{r}
#| message: false
#| echo: false
#| include: false
#reactable
library(tidyverse)
library(reactable)
library(here)
source(file.path("scripts", "list_to_data_frame_env.R"))


geocoded_dah <- read_rds(file.path("inputs", "geocoded_addreses.rds"))

as_tibble_env(geocoded_dah)
rm(geocoded_dah)
```

```{r}
#| label: demo_table
#| message: false
#| echo: false

all_addresses_geocoded %>%
  select(-city) %>%
  reactable(
    striped = TRUE,
    columns = list(
      docket_number = colDef(name = "Docket Number")),
    theme = reactableTheme(
      stripedColor = "#f6f8fa"
    )
  )
```

```{r}
#| label: map_data
#| include: false

library(sf)

addresses_sf <- all_addresses_geocoded %>% 
  filter(!is.na(lat)) %>%
  st_as_sf(coords = c("lat", "long"), crs = 4326)

```

```{r}
#| echo: false
#| message: false
library(leaflet)
library(mapboxapi)

city_icon <- makeAwesomeIcon(icon = "landmark", library = "fa",
                             iconColor = "white")

leaflet(addresses_sf) %>%
  setView(-87.6715046, 
          41.826966371014564, 
          zoom =10) %>%
    addAwesomeMarkers(lng = -87.6715046, 
                    lat = 41.826966371014564,
                    icon = city_icon) %>%
  addMapboxTiles(username = "mapbox",
                 style_id = "outdoors-v12") %>%
  addMarkers(data = addresses_sf)
```
